# =============================================================
#  interview_service.py  –  Interview Feedback Microservice
#  (FastAPI, Oracle-backed)
#  Run on its own port, e.g.  python interview_service.py
#  The Flask app (frontend/app.py) is a plain HTTP proxy in front
#  of this service — it does not touch Oracle or business logic
#  directly, matching app.py's other microservice proxy routes.
# =============================================================

import os
import pathlib
import statistics
from collections import defaultdict
from datetime import date

import oracledb
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# ------------------------------------------------------------------
# ENV LOADING  (same .env convention as app.py / clientcollabration.py)
# ------------------------------------------------------------------
_script_dir = pathlib.Path(__file__).resolve().parent
for _candidate in [
    _script_dir / ".env",
    _script_dir / ".env.txt",
    pathlib.Path.cwd() / ".env",
    pathlib.Path.cwd() / ".env.txt",
]:
    if _candidate.exists():
        load_dotenv(dotenv_path=_candidate, override=True)
        print(f"[interview_service] dotenv loaded: {_candidate}")
        break

# ------------------------------------------------------------------
# ORACLE CONFIG  (same host/user/password fallback convention as app.py)
# ------------------------------------------------------------------
ORACLE_HOST         = os.getenv("ORACLE_HOST", "56.228.73.210")
ORACLE_PORT         = int(os.getenv("ORACLE_PORT", "1521"))
ORACLE_SERVICE_NAME = os.getenv("ORACLE_SERVICE_NAME", "FREEPDB1")
ORACLE_USER         = os.getenv("ORACLE_USER", "SUPPORT")
ORACLE_PASSWORD     = os.getenv("ORACLE_PASSWORD", "Welcome123")


def get_connection():
    dsn = oracledb.makedsn(ORACLE_HOST, ORACLE_PORT, service_name=ORACLE_SERVICE_NAME)
    conn = oracledb.connect(user=ORACLE_USER, password=ORACLE_PASSWORD, dsn=dsn)

    cur = conn.cursor()
    cur.execute("ALTER SESSION SET CURRENT_SCHEMA = CHAKORA")
    cur.close()

    return conn


# ------------------------------------------------------------------
# SCHEMA  (idempotent create — works whether or not the table exists)
# ------------------------------------------------------------------
CREATE_TABLE_SQL = """
CREATE TABLE interview_feedback (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_name    VARCHAR2(200) NOT NULL,
    position          VARCHAR2(200) NOT NULL,
    interview_round   VARCHAR2(100) NOT NULL,
    interviewer_name  VARCHAR2(200) NOT NULL,
    interview_date    VARCHAR2(20)  NOT NULL,
    technical_skills  NUMBER(1) NOT NULL,
    problem_solving   NUMBER(1) NOT NULL,
    communication     NUMBER(1) NOT NULL,
    culture_fit       NUMBER(1) NOT NULL,
    recommendation    VARCHAR2(40) NOT NULL,
    comments          VARCHAR2(4000),
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP
)
"""

SEED_ROWS = [
    ("Ananya Rao", "Backend Engineer", "Screening", "Priya Nair", "2026-07-01", 4, 4, 5, 4, "Hire",
     "Strong fundamentals in Python and system design basics. Communicated clearly."),
    ("Ananya Rao", "Backend Engineer", "Technical Round 1", "Karthik Iyer", "2026-07-03", 5, 4, 4, 4, "Strong Hire",
     "Excellent grasp of data structures. Solved the coding problem optimally."),
    ("Ananya Rao", "Backend Engineer", "Hiring Manager Round", "Divya Menon", "2026-07-08", 4, 4, 5, 5, "Strong Hire",
     "Great culture fit, asked thoughtful questions about the team."),
    ("Rahul Sharma", "Frontend Engineer", "Screening", "Priya Nair", "2026-07-01", 3, 3, 4, 4, "Hire",
     "Decent JavaScript fundamentals but needs to brush up on React internals."),
    ("Rahul Sharma", "Frontend Engineer", "Technical Round 1", "Neha Gupta", "2026-07-02", 2, 3, 3, 3, "No Hire",
     "Struggled with the component state management exercise."),
    ("Vikram Desai", "Data Analyst", "Screening", "Sandeep Verma", "2026-07-02", 4, 4, 4, 5, "Hire",
     "Solid SQL skills demonstrated in the screening exercise."),
    ("Vikram Desai", "Data Analyst", "Technical Round 1", "Divya Menon", "2026-07-06", 5, 5, 4, 5, "Strong Hire",
     "Outstanding SQL and analytical thinking."),
]


def init_db(seed_if_empty: bool = True):
    conn = get_connection()
    try:
        cur = conn.cursor()
        try:
            cur.execute(CREATE_TABLE_SQL)
            conn.commit()
            print("[interview_service] created 'interview_feedback' table")
        except oracledb.DatabaseError as exc:
            (error,) = exc.args
            if error.code != 955:  # ORA-00955: name already used by an existing object
                raise

        if seed_if_empty:
            cur.execute("SELECT COUNT(*) FROM interview_feedback")
            (count,) = cur.fetchone()
            if count == 0:
                cur.executemany(
                    """INSERT INTO interview_feedback
                       (candidate_name, position, interview_round, interviewer_name, interview_date,
                        technical_skills, problem_solving, communication, culture_fit, recommendation, comments)
                       VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10, :11)""",
                    SEED_ROWS,
                )
                conn.commit()
                print(f"[interview_service] seeded {len(SEED_ROWS)} sample rows")
    finally:
        conn.close()


# ------------------------------------------------------------------
# AGGREGATION  (same logic as the original aggregate.py)
# ------------------------------------------------------------------
SCORE_FIELDS = ["technical_skills", "problem_solving", "communication", "culture_fit"]
FIELD_LABELS = {
    "technical_skills": "Technical Skills",
    "problem_solving": "Problem Solving",
    "communication": "Communication",
    "culture_fit": "Culture Fit",
}
REC_TO_SCORE = {"Strong Hire": 4, "Hire": 3, "No Hire": 2, "Strong No Hire": 1}
SCORE_TO_REC = {v: k for k, v in REC_TO_SCORE.items()}
POSITIVE_RECS = {"Hire", "Strong Hire"}
NEGATIVE_RECS = {"No Hire", "Strong No Hire"}


def _final_recommendation(recs):
    has_positive = any(r in POSITIVE_RECS for r in recs)
    has_negative = any(r in NEGATIVE_RECS for r in recs)
    if has_positive and has_negative:
        return "Split Decision - Needs Discussion"
    avg = statistics.mean(REC_TO_SCORE[r] for r in recs)
    rounded = min(max(round(avg), 1), 4)
    return SCORE_TO_REC[rounded]


def consolidate(rows):
    by_candidate = defaultdict(list)
    for row in rows:
        by_candidate[row["candidate_name"]].append(row)

    results = []
    for candidate, entries in by_candidate.items():
        position = entries[-1]["position"]
        dim_avgs = {
            FIELD_LABELS[f]: round(statistics.mean(e[f] for e in entries), 2)
            for f in SCORE_FIELDS
        }
        overall_avg = round(statistics.mean(dim_avgs.values()), 2)
        recs = [e["recommendation"] for e in entries]
        final_rec = _final_recommendation(recs)

        results.append({
            "candidate": candidate,
            "position": position,
            "rounds_completed": len(entries),
            "dimension_averages": dim_avgs,
            "overall_average": overall_avg,
            "final_recommendation": final_rec,
        })

    results.sort(key=lambda r: r["overall_average"], reverse=True)
    return results


# ------------------------------------------------------------------
# DATA ACCESS
# ------------------------------------------------------------------
def _row_to_dict(cursor, row):
    columns = [d[0].lower() for d in cursor.description]
    return dict(zip(columns, row))


def get_all_feedback():
    conn = get_connection()
    try:
        cur = conn.cursor()
        cur.execute("SELECT * FROM interview_feedback ORDER BY interview_date ASC, id ASC")
        return [_row_to_dict(cur, r) for r in cur.fetchall()]
    finally:
        conn.close()


def get_candidate_feedback(candidate_name: str):
    conn = get_connection()
    try:
        cur = conn.cursor()
        cur.execute(
            "SELECT * FROM interview_feedback WHERE candidate_name = :1 ORDER BY interview_date ASC, id ASC",
            [candidate_name],
        )
        return [_row_to_dict(cur, r) for r in cur.fetchall()]
    finally:
        conn.close()


def get_feedback_by_id(feedback_id: int):
    conn = get_connection()
    try:
        cur = conn.cursor()
        cur.execute("SELECT * FROM interview_feedback WHERE id = :1", [feedback_id])
        row = cur.fetchone()
        return _row_to_dict(cur, row) if row else None
    finally:
        conn.close()


def insert_feedback(data: dict):
    conn = get_connection()
    try:
        cur = conn.cursor()
        cur.execute(
            """INSERT INTO interview_feedback
               (candidate_name, position, interview_round, interviewer_name, interview_date,
                technical_skills, problem_solving, communication, culture_fit, recommendation, comments)
               VALUES (:candidate_name, :position, :interview_round, :interviewer_name, :interview_date,
                       :technical_skills, :problem_solving, :communication, :culture_fit, :recommendation, :comments)""",
            data,
        )
        conn.commit()
    finally:
        conn.close()


def update_feedback(feedback_id: int, data: dict):
    conn = get_connection()
    try:
        cur = conn.cursor()
        cur.execute(
            """UPDATE feedback SET
                   candidate_name = :candidate_name,
                   position = :position,
                   interview_round = :interview_round,
                   interviewer_name = :interviewer_name,
                   interview_date = :interview_date,
                   technical_skills = :technical_skills,
                   problem_solving = :problem_solving,
                   communication = :communication,
                   culture_fit = :culture_fit,
                   recommendation = :recommendation,
                   comments = :comments
               WHERE id = :id""",
            {**data, "id": feedback_id},
        )
        conn.commit()
    finally:
        conn.close()


def delete_candidate(candidate_name: str):
    conn = get_connection()
    try:
        cur = conn.cursor()
        cur.execute("DELETE FROM interview_feedback WHERE candidate_name = :1", [candidate_name])
        conn.commit()
    finally:
        conn.close()


def delete_feedback_entry(feedback_id: int):
    conn = get_connection()
    try:
        cur = conn.cursor()
        cur.execute("DELETE FROM interview_feedback WHERE id = :1", [feedback_id])
        conn.commit()
    finally:
        conn.close()


# ------------------------------------------------------------------
# FASTAPI APP
# ------------------------------------------------------------------
app = FastAPI(title="Interview Feedback Microservice")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # tighten this to the Flask front end's origin in production
    allow_methods=["*"],
    allow_headers=["*"],
)


class FeedbackIn(BaseModel):
    candidate_name: str
    position: str
    interview_round: str
    interviewer_name: str
    interview_date: str
    technical_skills: int
    problem_solving: int
    communication: int
    culture_fit: int
    recommendation: str
    comments: str = ""


@app.on_event("startup")
def on_startup():
    init_db(seed_if_empty=True)


@app.get("/health")
def health():
    return {"service": "interview_service", "status": "healthy"}


@app.get("/api/interview/feedback")
def api_all_feedback():
    """Every raw row + the per-candidate consolidated view (dashboard needs both)."""
    rows = get_all_feedback()
    return {
        "rows": rows,
        "candidates": consolidate(rows) if rows else [],
        "total_submissions": len(rows),
    }


@app.get("/api/interview/candidate/{candidate_name}")
def api_candidate_detail(candidate_name: str):
    rows = get_candidate_feedback(candidate_name)
    if not rows:
        raise HTTPException(status_code=404, detail="Candidate not found")
    summary = consolidate(rows)[0]
    return {"candidate": summary, "rounds": rows}


@app.post("/api/interview/feedback", status_code=201)
def api_submit_feedback(payload: FeedbackIn):
    data = payload.model_dump()
    data["candidate_name"] = data["candidate_name"].strip()
    data["comments"] = data["comments"].strip()
    insert_feedback(data)
    return {"candidate_name": data["candidate_name"]}


@app.get("/api/interview/feedback/{feedback_id}")
def api_get_feedback(feedback_id: int):
    entry = get_feedback_by_id(feedback_id)
    if not entry:
        raise HTTPException(status_code=404, detail="Feedback entry not found")
    return entry


@app.put("/api/interview/feedback/{feedback_id}")
def api_update_feedback(feedback_id: int, payload: FeedbackIn):
    if not get_feedback_by_id(feedback_id):
        raise HTTPException(status_code=404, detail="Feedback entry not found")
    data = payload.model_dump()
    data["candidate_name"] = data["candidate_name"].strip()
    data["comments"] = data["comments"].strip()
    update_feedback(feedback_id, data)
    return {"candidate_name": data["candidate_name"]}


@app.delete("/api/interview/feedback/{feedback_id}")
def api_delete_feedback(feedback_id: int):
    entry = get_feedback_by_id(feedback_id)
    if not entry:
        raise HTTPException(status_code=404, detail="Feedback entry not found")
    delete_feedback_entry(feedback_id)
    remaining = get_candidate_feedback(entry["candidate_name"])
    return {"candidate_name": entry["candidate_name"], "candidate_has_remaining_rounds": bool(remaining)}


@app.delete("/api/interview/candidate/{candidate_name}")
def api_delete_candidate(candidate_name: str):
    delete_candidate(candidate_name)
    return {"status": "deleted", "candidate_name": candidate_name}


if __name__ == "__main__":
    import uvicorn
    print("[interview_service] starting FastAPI app on port 8003")
    uvicorn.run("interview_service:app", host="0.0.0.0", port=8003, reload=True)
